version: '3.9'

services:
  postgresqldatabase:
    image: bitnami/postgresql
    ports:
      - 5432
    environment:
      - POSTGRES_USER=parcial
      - POSTGRES_PASSWORD=parcial
      - POSTGRES_DB=parcial

  webpage:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=composed